### ISSUE TITLE
Turning it up to ELEVEN - the TO-DO thread

### ISSUE THREAD

**Issue by hackedpassword** [hackedpassword/Z2#11]
- [ ] Create promotion icons
- [ ] Alias Unciv resources - > Z2 items (temp til recreated as native)
- [ ] Differentiate Forage vs Farm
- [ ] Evo Slog mud
- [ ] Lancer upgrade path sucks, is chaotic
- [ ] Formation promotion will Evo to say armored units
- [ ] Fix sword unit and Villager Fight enemies!
- [ ] Cavern resource allowances
- [ ] City center canBeBuiltOn - core gameplay mechanic
- [ ] Prehistoric Villager sprite
- [ ] Z2-specific sprites shown in civopedia
